# Generated by Django 3.2.21 on 2023-09-14 18:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='recipe_dislike', to=settings.AUTH_USER_MODEL),
        ),
    ]
